In [ ]:
# prompt: looks like there is seperator in the excel file., break it into different columns

import pandas as pd

!pip install openpyxl
df = pd.read_excel('/content/Online retail.xlsx', names=['items']) # Assuming file is in the same directory

# Assuming the separator is ';' and the column to split is 'Description'
df_split = df['items'].str.split(',', expand=True)



print(df_split.head())

Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/dist-packages (from openpyxl) (2.0.0)
               0          1           2                 3          4     5   \
0         burgers  meatballs        eggs              None       None  None
1         chutney       None        None              None       None  None
2          turkey    avocado        None              None       None  None
3   mineral water       milk  energy bar  whole wheat rice  green tea  None
4  low fat yogurt       None        None              None       None  None

     6     7     8     9     10    11    12    13    14    15    16    17  \
0  None  None  None  None  None  None  None  None  None  None  None  None
1  None  None  None  None  None  None  None  None  None  None  None  None
2  None  None  None  None  None  None  None  None  None  None  None  None
3  None  None  None  None  None  None  None  None  None  None  None  None
4  None  None  None  None  None  None  None  None  None  None  None  None

     18
0  None
1  None
2  None
3  None
4  None

In [ ]:
import numpy as np
dataset = df_split.replace(np.nan, '', regex=True)
dataset

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,burgers,meatballs,eggs,,,,,,,,,,,,,,,,
1,chutney,,,,,,,,,,,,,,,,,,
2,turkey,avocado,,,,,,,,,,,,,,,,,
3,mineral water,milk,energy bar,whole wheat rice,green tea,,,,,,,,,,,,,,
4,low fat yogurt,,,,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,butter,light mayo,fresh bread,,,,,,,,,,,,,,,,
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,,,,,,,,,,,,,
7497,chicken,,,,,,,,,,,,,,,,,,
7498,escalope,green tea,,,,,,,,,,,,,,,,,
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,,,,,,,,,,,,,,,

In [ ]:
transactions = []
for i in range(0, 7500):
    # Change the range of u to 0 to 19 (exclusive) or 0 to dataset.shape[1]
    transactions.append([str(dataset.values[i,u]) for u in range(0, dataset.shape[1])])

In [ ]:
transactions

NameError: name 'transactions' is not defined

In [ ]:
groceries_series  = pd.DataFrame(pd.Series(transactions))
groceries_series
groceries_series.columns = ["business"]
groceries_series

NameError: name 'transactions' is not defined

In [ ]:
X = groceries_series['business'].str.join(sep=',').str.get_dummies(sep=',')
X

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0